[scene.library]
name = "library"
background = "example-game/assets/scene/library.bmp"

[scene.meeting-room]
name = "meeting-room"
background = "example-game/assets/scene/meeting-room.bmp"

[scene.cafeteria]
name = "cafeteria"
background = "example-game/assets/scene/cafeteria.bmp"

[character.classmate]
name = "Alice (your classmate)"
avatar = "example-game/assets/character/alice/avatar.bmp"
tachie = "example-game/assets/character/alice/tachie.bmp"   

[character.ta]
location = "meeting-room"
name = "Teaching Assistant"
avatar = "example-game/assets/character/ta/avatar.bmp" 
tachie = "example-game/assets/character/ta/tachie.bmp"

[character.librarian]
location = "library"
name = "Librarian"
avatar = "example-game/assets/character/librarian/avatar.bmp"
tachie = "example-game/assets/character/librarian/tachie.bmp"

[item.vision-pro]
name = "Vision Pro"
description = "A spatial computer"
icon = "example-game/assets/item/vision-pro/icon.bmp"

[item.book]  
name = "Old Book"
description = "A mysterious old book"
icon = "example-game/assets/item/book/icon.bmp"

[event.start]
scene = "library"
dialogue = "hello"

[dialogue.hello]
scene = "library"
character = "classmate"
text = "嗨！聽說今年的期末專題要做互動式小說引擎喔～"
[[dialogue.hello.options]]
text = "哇！太棒了！"
next = "find_book"
[[dialogue.hello.options]]
text = "那是啥鬼？"
next = "explanation"

[dialogue.explanation]
scene = "library"
character = "classmate"
text = "就是一個讓你創建和玩你自己故事的遊戲平台。聽起來有點複雜，但應該蠻有趣的！"
[[dialogue.explanation.options]]
text = "聽起來不錯，告訴我更多！" 
next = "find_book"
[[dialogue.explanation.options]]
text = "好吧，我可能會需要幫助。"
next = "find_book"

[dialogue.find_book]
scene = "library"
character = "librarian"
text = "你好！這是你需要的那本書。"
event = "acquire_book"

[event.acquire_book]
action = "add_item"
item = "book"
dialogue = "book_acquired"

[dialogue.book_acquired]
scene = "library"
character = "classmate"
text = "太好了！這本書看起來很有幫助。"
[[dialogue.book_acquired.options]]
text = "我們開始閱讀吧。"
next = "read_book"
[[dialogue.book_acquired.options]]
text = "先去會議室找助教，看看他有什麼建議。"
next = "ta_intro"

[dialogue.read_book]
scene = "library"
character = "classmate"
text = "我們找到了關於專案的一些關鍵資訊，這本書真是太有用了。"
[[dialogue.read_book.options]]
text = "繼續努力，完成我們的專案吧！"
next = "project_start"
[[dialogue.read_book.options]]
text = "我們還需要更多資料。"
next = "find_more_books"

[event.project_start]
scene = "library"
dialogue = "start_working"

[dialogue.start_working]
scene = "library"
character = "classmate"
text = "我們開始工作吧！"
[[dialogue.start_working.options]]
text = "好，我們先分工合作。"
next = "work_division"
[[dialogue.start_working.options]]
text = "我們先列出所有需要做的事情。"
next = "task_listing"

[dialogue.work_division]
scene = "library"
character = "classmate"
text = "你負責劇本，我負責程式。我們兩週後再來討論進度。"
[[dialogue.work_division.options]]
text = "好的，沒問題！"
next = "project_progress_good"
[[dialogue.work_division.options]]
text = "我覺得我們需要更多時間。"
next = "project_progress_bad"

[dialogue.task_listing]
scene = "library"
character = "classmate"
text = "我們列出了一個詳細的計劃，並按部就班地完成了所有工作。"
[[dialogue.task_listing.options]]
text = "太棒了，讓我們開始吧！"
next = "project_progress_good"
[[dialogue.task_listing.options]]
text = "這計劃太複雜了，我們需要簡化一下。"
next = "project_progress_neutral"

[dialogue.project_progress_good]
scene = "library"
character = "classmate"
text = "經過兩週的努力,我們的專案進展非常順利,完成了大部分的任務。"
[[dialogue.project_progress_good.options]]
text = "太好了,讓我們繼續保持下去!"
next = "ending_good"

[dialogue.project_progress_bad]
scene = "library"
character = "classmate"
text = "兩週過去了,我們的進度有點落後。我們需要加把勁了。"
[[dialogue.project_progress_bad.options]]
text = "我們需要重新調整計劃,爭取按時完成。"
next = "ending_neutral"
[[dialogue.project_progress_bad.options]]
text = "看來我們無法按時完成了。"
next = "ending_bad"

[dialogue.project_progress_neutral]
scene = "library"
character = "classmate"
text = "經過兩週,我們完成了計劃的一部分,但還有一些工作需要完成。"
[[dialogue.project_progress_neutral.options]]
text = "讓我們集中精力,完成剩下的部分。"
next = "ending_neutral"

[dialogue.ending_good]
scene = "library"
character = "classmate"
text = "恭喜！你們成功完成了期末專題，並得到了老師的高度評價。"
event = "game_over_good"

[dialogue.ending_bad]
scene = "library"
character = "classmate"
text = "很遺憾，你們的期末專題沒能按時完成，最終沒能通過。"
event = "game_over_bad"

[dialogue.ending_neutral]
scene = "library"
character = "classmate"
text = "你們的期末專題最終完成了，但因為時間和資源的限制，只得到了中等評價。"
event = "game_over_neutral"

[event.game_over_good]
action = "end_game"
result = "good"

[event.game_over_bad]
action = "end_game"
result = "bad"

[event.game_over_neutral]
action = "end_game"
result = "neutral"

[dialogue.find_more_books]
scene = "library"
character = "classmate"
text = "我們去找找其他的書，看看能不能找到更多有用的資料。"
[[dialogue.find_more_books.options]]
text = "好的，繼續找書。"
next = "book_search"
[[dialogue.find_more_books.options]]
text = "先去會議室討論我們目前的進展吧。"
next = "ta_intro"

[dialogue.book_search]
scene = "library"
character = "librarian"
text = "這是我能找到的所有相關書籍，希望對你們有幫助。"
[[dialogue.book_search.options]]
text = "謝謝，我們會仔細閱讀的。"
next = "read_more_books"
[[dialogue.book_search.options]]
text = "我們需要更多的幫助，先去找助教討論。"
next = "ta_intro"

[dialogue.read_more_books]
scene = "library"
character = "classmate"
text = "這些書籍提供了很多有用的信息，我們可以開始動手做了。"
[[dialogue.read_more_books.options]]
text = "讓我們開始實作吧！"
next = "project_progress_good"
[[dialogue.read_more_books.options]]
text = "先去會議室討論我們目前的進展吧。"
next = "ta_intro"
